---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600  # Allow time for pvc->snap->pvc
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,pvc,volumesnapshot,replicationsource,replicationdestination

---
apiVersion: batch/v1
kind: Job
metadata:
  name: write-data
status:
  succeeded: 1
