apiVersion: batch/v1
kind: Job
metadata:
  name: write-data
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: writer
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["echo 'hello world' > /data/testdata.txt"]
        volumeMounts:
        - name: test-data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: test-data
        persistentVolumeClaim:
          claimName: test-data-1
