apiVersion: batch/v1
kind: Job
metadata:
  name: verify-data
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: verifier
        image: alpine
        # verifies that "hello world" is written to the test-data pvc
        command: ["/bin/sh", "-c"]
        args: ["cat /data/testdata.txt | grep 'hello world'"]
        volumeMounts:
        - name: test-data
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: test-data
        persistentVolumeClaim:
          claimName: test-data

