apiVersion: batch/v1
kind: Job
metadata:
  name: read-data
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: reader
        image: alpine
        # validate that the testdata file contains "hello world"
        command: ["/bin/sh", "-c"]
        args: ["cat /data/testdata.txt | grep 'hello world'"]
        volumeMounts:
        - name: test-data
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: test-data
        persistentVolumeClaim:
          claimName: test-data-2
