apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: syncthing-test
spec:
  sourcePVC: mysql-pv-claim
  # trigger:
  #   manual: my-trigger
  syncthing:
    peerList:
      - address: tcp://address
        ID: DA3Q6BT-IOETIDC-SUS2BY4-VSSQP7B-MTD2VUM-XMX6ZKG-4GXGVNP-EPMW5QH


